//Arquivo de melodias:

//MISSAO IMPOSSIVEL:
int missao[]={
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_AS4, SEMINIMA, NOTE_C5, SEMINIMA,
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_F4, SEMINIMA, NOTE_FS4, SEMINIMA,
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_AS4, SEMINIMA, NOTE_C5, SEMINIMA,
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_F4, SEMINIMA, NOTE_FS4, SEMINIMA,

NOTE_B5, COLCHEIA, NOTE_G5, COLCHEIA, NOTE_D5, SEMIBREVE,
NOTE_B5, COLCHEIA, NOTE_G5, COLCHEIA, NOTE_CS4, SEMIBREVE,
NOTE_B5, COLCHEIA, NOTE_G5, COLCHEIA, NOTE_C4, SEMIBREVE,
NOTE_B4, COLCHEIA, NOTE_C4, COLCHEIA, PAUSA, SEMIBREVE,

NOTE_B4, COLCHEIA, NOTE_G4, COLCHEIA, NOTE_FS5, SEMIBREVE,
NOTE_B4, COLCHEIA, NOTE_G4, COLCHEIA, NOTE_F5, SEMIBREVE,
NOTE_B4, COLCHEIA, NOTE_G4, COLCHEIA, NOTE_E5, SEMIBREVE,
NOTE_E5, COLCHEIA, NOTE_D5, COLCHEIA, PAUSA, SEMIBREVE,


NOTE_E5, COLCHEIA, NOTE_C4, COLCHEIA, NOTE_G4, SEMIBREVE,
NOTE_E5, COLCHEIA, NOTE_C4, COLCHEIA, NOTE_FS4, SEMIBREVE,
NOTE_E5, COLCHEIA, NOTE_C4, COLCHEIA, NOTE_F4, SEMIBREVE,
NOTE_E4, COLCHEIA, NOTE_F4, COLCHEIA, PAUSA, SEMIBREVE,

NOTE_B5, COLCHEIA, NOTE_G5, COLCHEIA, NOTE_D5, SEMIBREVE,
NOTE_B5, COLCHEIA, NOTE_G5, COLCHEIA, NOTE_CS4, SEMIBREVE,
NOTE_B5, COLCHEIA, NOTE_G5, COLCHEIA, NOTE_C4, SEMIBREVE,
NOTE_B4, COLCHEIA, NOTE_C4, COLCHEIA, PAUSA, SEMIBREVE,


NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_AS4, SEMINIMA, NOTE_C5, SEMINIMA,
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_F4, SEMINIMA, NOTE_FS4, SEMINIMA,
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_AS4, SEMINIMA, NOTE_C5, SEMINIMA,
NOTE_G4, SEMINIMA, PAUSA, COLCHEIA, NOTE_G4, COLCHEIA+SEMINIMA, NOTE_F4, SEMINIMA, NOTE_FS4, SEMINIMA,
NOTE_G4, MINIMA, PAUSA, SEMIBREVE
};

int qtdNotasMissao = sizeof(missao) / sizeof(missao[0]) / 2;

//-----
