//Arquivo de melodias:

/*
SOS = *.*.*._._._.*.*.*.

SOS = .p.p.P_p_p_P.p.p.
p = FUSA
P = SEMICOLCHEIA
. = SEMICOLCHEIA
_ = COLCHEIA
freq: ~ 600Hz
*/
int sos[]={
NOTE_D5, SEMICOLCHEIA,
PAUSA, FUSA,
NOTE_D5, SEMICOLCHEIA,
PAUSA, FUSA,
NOTE_D5, SEMICOLCHEIA,

PAUSA, SEMICOLCHEIA,

NOTE_D5, COLCHEIA,
PAUSA, FUSA,
NOTE_D5, COLCHEIA,
PAUSA, FUSA,
NOTE_D5, COLCHEIA,

PAUSA, SEMICOLCHEIA,

NOTE_D5, SEMICOLCHEIA,
PAUSA, FUSA,
NOTE_D5, SEMICOLCHEIA,
PAUSA, FUSA,
NOTE_D5, SEMICOLCHEIA,

};

int qtdNotasSOS = sizeof(sos) / sizeof(sos[0]) / 2;

//-----